### ISSUE TITLE
消息输出问题

### ISSUE THREAD

**Issue by YouYouLip** [mmxd12/nonebot_plugin_warframe_mode#1]
使用时出现了[WARNING]: 警告: 非法 Forward node 将跳过. uin: 2907336149 name: 这里是WFBOT content count: 0
凡是群聊信息都会出现
![image](https://user-images.githubusercontent.com/119958263/229960200-ce3cc7fe-552b-4b99-8407-efdb4e7b1cba.png)
看了一下bot输出是响应了该插件但是并没有反应

**Comment by YouYouLip** [comment]
python是3.10.9
gocq反馈的是[WARNING]: 警告: 非法 Forward node 将跳过. uin: 2907336149 name: 这里是WFBOT content count: 0
使用的是ipad的协议

**Comment by YouYouLip** [comment]
更新
![image](https://user-images.githubusercontent.com/119958263/229971189-441b17bc-bb6e-436f-a7d3-550426cbf179.png)
现在变成这样了 打折转发聊天记录在手机上可以看见 电脑显示异常

**Comment by YouYouLip** [comment]
不过应该是qq的问题 话说[WARNING]: 警告: 非法 Forward node 将跳过. uin: 2907336149 name: 这里是WFBOT content count: 0报错是因为检测到和wm插件无关的命令所跳过吗？不然我觉得不会发一个空的聊天记录

**Comment by YouYouLip** [comment]
![image](https://user-images.githubusercontent.com/119958263/229974270-8d14558a-3bc9-4cf6-b663-2d2741d6c219.png)
应该是该插件的问题？

**Comment by mmxd12** [comment]
我在这边测试了，发123是不会触发我插件的，只有发表情/开头的，合并消息可能在pc端有点问题，有时会看不懂，目前还没办法，后续会添加其他消息类型

**Comment by YouYouLip** [comment]
> 我在这边测试了，发123是不会触发我插件的，只有发表情/开头的，合并消息可能在pc端有点问题，有时会看不懂，目前还没办法，后续会添加其他消息类型

很迷啊 那应该...不会是gocq的问题吧 毕竟报错信息来源是gocq

**Comment by mmxd12** [comment]
目前只有表情触发/前缀，你可以把报错截图或者log发我看看

**Comment by YouYouLip** [comment]
> 

应该是gocq版本问题吧...出现这个报错我用的是1.0.0 后续切换1.0.0-rc5还是rc4都登不上gocq了 切换什么协议都登不上。。。

**Comment by mmxd12** [comment]
切换到1.0.0-rc5然后在本地Android Watch扫码就可以登上

**Comment by YouYouLip** [comment]
> 切换到1.0.0-rc5然后在本地Android Watch扫码就可以登上

已切换 但还是有这个报错
![image](https://user-images.githubusercontent.com/119958263/229979985-c78f2a87-d331-4173-a99d-baeb911949ec.png)

**Comment by YouYouLip** [comment]
·

> 切换到1.0.0-rc5然后在本地Android Watch扫码就可以登上

而且 不是什么123才能触发 是只要有人在群里说话 只要不是wm的指令就会触发 所以很迷

**Comment by mmxd12** [comment]
具体信息你可以加群435021808，我不能一直回你lssues

**Comment by YouYouLip** [comment]
> 具体信息你可以加群435021808，我不能一直回你lssues

了解 但是这种情况我其实觉得还是因为该插件的问题，应该不是gocq的了 毕竟gocq版本都换过试过了 所以....希望有空的时候能检测检测 这个问题在我之前使用的时候还没有 家里挂服务器的台式重装了一次系统后就这样了 我隐约记得是rc4版本的时候....我再去试试看吧

**Comment by mmxd12** [comment]
新版本已经更新了你可以(pip install -U  nonebot_plugin_warframe_mode -i https://pypi.python.org/simple)使用官方源更新，国内源可能还没那么快出[](https://pypi.org/project/nonebot-plugin-warframe-mode/)

**Comment by YouYouLip** [comment]
> 新版本已经更新了你可以(pip install -U nonebot_plugin_warframe_mode -i [https://pypi.python.org/simple)使用官方源更新，国内源可能还没那么快出[](https://pypi.org/project/nonebot-plugin-warframe-mode/](https://pypi.python.org/simple)%E4%BD%BF%E7%94%A8%E5%AE%98%E6%96%B9%E6%BA%90%E6%9B%B4%E6%96%B0%EF%BC%8C%E5%9B%BD%E5%86%85%E6%BA%90%E5%8F%AF%E8%83%BD%E8%BF%98%E6%B2%A1%E9%82%A3%E4%B9%88%E5%BF%AB%E5%87%BA%5B%5D(https://pypi.org/project/nonebot-plugin-warframe-mode/))

感谢 问题没有复现了
