### ISSUE TITLE
小工具很好用，但是会出现无法查看的问题，如图

### ISSUE THREAD

**Issue by 360add** [mmxd12/nonebot_plugin_warframe_mode#2]
![QQ截图20230821165725](https://github.com/mmxd12/nonebot_plugin_warframe_mode/assets/140232510/2759cf94-d4e5-4e39-a126-f0fe78ce7365)
![QQ截图20230821170711](https://github.com/mmxd12/nonebot_plugin_warframe_mode/assets/140232510/221c9030-1d06-4f14-9b8c-005390220e13)
目前只有裂缝会这样

**Comment by mmxd12** [comment]
是每次都出现还是说时不时，如果是时不时出现太概率是被屏蔽了

**Comment by 360add** [comment]
时不时出现，而且只有发裂缝会出现这个问题

**Comment by 360add** [comment]
[
![QQ截图20230821174428](https://github.com/mmxd12/nonebot_plugin_warframe_mode/assets/140232510/939d38f6-d673-498f-8bee-0fd24dc4f988)
lie'f裂缝是一直没法查看

**Comment by 360add** [comment]
下午刚用的时候没法看裂缝，然后突然好了一会，重启了nb又没法看裂缝了

**Comment by mmxd12** [comment]
那就是被风控了，因为裂缝都是长消息

**Comment by 360add** [comment]
如果可以转为如片发送就好了，大佬加油
