### ISSUE TITLE
请问网址该怎么配置

### ISSUE THREAD

**Issue by hdjsadgfwtg** [mmxd12/nonebot_plugin_warframe_mode#5]
nymph.rbq.life看起来像是大佬的网址，现在不维护了，可否告知一下该如何配置，我正在弄一个基于官方qq的wfbot。（虽然限制很多）

**Comment by mmxd12** [comment]
在data_source.py这里找到get_data_api这里是改网址，如果是wm，rm这些是在__init__.py里面

**Comment by hajisensai** [comment]
> 在data_source.py这里找到get_data_api这里是改网址，如果是wm，rm这些是在__init__.py里面

佬你这个中转的是哪个网站呢？是wm的api吗？

**Comment by mmxd12** [comment]
[https://github.com/WsureWarframe/warframe-info-api](url)

**Comment by hajisensai** [comment]
谢谢
